version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./Backend:/FINANCE-DASHBOARD/BACKEND
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://finance-dashboard-backend-6i92.onrender.com/api/v1
    volumes:
      - ./Frontend:/FINANCE-DASHBOARD/FRONTEND
      - /FINANCE-DASHBOARD/FRONTEND/node_modules
    depends_on:
      - backend
    restart: unless-stopped
